/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xeij_WinDLL */

#ifndef _Included_xeij_WinDLL
#define _Included_xeij_WinDLL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xeij_WinDLL
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xeij_WinDLL_version
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
