/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xeij_NamedPipeInputStream_Win */

#ifndef _Included_xeij_NamedPipeInputStream_Win
#define _Included_xeij_NamedPipeInputStream_Win
#ifdef __cplusplus
extern "C" {
#endif
#undef xeij_NamedPipeInputStream_Win_MAX_SKIP_BUFFER_SIZE
#define xeij_NamedPipeInputStream_Win_MAX_SKIP_BUFFER_SIZE 2048L
#undef xeij_NamedPipeInputStream_Win_DEFAULT_BUFFER_SIZE
#define xeij_NamedPipeInputStream_Win_DEFAULT_BUFFER_SIZE 16384L
#undef xeij_NamedPipeInputStream_Win_MAX_BUFFER_SIZE
#define xeij_NamedPipeInputStream_Win_MAX_BUFFER_SIZE 2147483639L
/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xeij_NamedPipeInputStream_00024Win_available
  (JNIEnv *, jobject);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_NamedPipeInputStream_00024Win_cancel
  (JNIEnv *, jobject);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_NamedPipeInputStream_00024Win_close
  (JNIEnv *, jobject);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_NamedPipeInputStream_00024Win_connect
  (JNIEnv *, jobject);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xeij_NamedPipeInputStream_00024Win_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xeij_NamedPipeInputStream_00024Win_read__
  (JNIEnv *, jobject);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_xeij_NamedPipeInputStream_00024Win_read___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_xeij_NamedPipeInputStream_00024Win_read___3BII
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     xeij_NamedPipeInputStream_Win
 * Method:    readNBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_xeij_NamedPipeInputStream_00024Win_readNBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
