/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xeij_OldSerialPort */

#ifndef _Included_xeij_OldSerialPort
#define _Included_xeij_OldSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xeij_OldSerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_close
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort
 * Method:    getInputStream
 * Signature: ()Lxeij/OldSerialPort/SerialInputStream;
 */
JNIEXPORT jobject JNICALL Java_xeij_OldSerialPort_getInputStream
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort
 * Method:    getOutputStream
 * Signature: ()Lxeij/OldSerialPort/SerialOutputStream;
 */
JNIEXPORT jobject JNICALL Java_xeij_OldSerialPort_getOutputStream
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort
 * Method:    getPortName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_xeij_OldSerialPort_getPortName
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_open__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     xeij_OldSerialPort
 * Method:    open
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_open__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     xeij_OldSerialPort
 * Method:    speed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_speed
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
