/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xeij_ZKeyLEDPort */

#ifndef _Included_xeij_ZKeyLEDPort
#define _Included_xeij_ZKeyLEDPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xeij_ZKeyLEDPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_ZKeyLEDPort_close
  (JNIEnv *, jobject);

/*
 * Class:     xeij_ZKeyLEDPort
 * Method:    hitKey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xeij_ZKeyLEDPort_hitKey
  (JNIEnv *, jobject, jint);

/*
 * Class:     xeij_ZKeyLEDPort
 * Method:    isKeyPressed
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_xeij_ZKeyLEDPort_isKeyPressed
  (JNIEnv *, jobject, jint);

/*
 * Class:     xeij_ZKeyLEDPort
 * Method:    isKeyToggled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_xeij_ZKeyLEDPort_isKeyToggled
  (JNIEnv *, jobject, jint);

/*
 * Class:     xeij_ZKeyLEDPort
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_ZKeyLEDPort_open
  (JNIEnv *, jobject);

/*
 * Class:     xeij_ZKeyLEDPort
 * Method:    send
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_xeij_ZKeyLEDPort_send
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
