/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xeij_OldSerialPort_SerialOutputStream */

#ifndef _Included_xeij_OldSerialPort_SerialOutputStream
#define _Included_xeij_OldSerialPort_SerialOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xeij_OldSerialPort_SerialOutputStream
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_00024SerialOutputStream_close
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort_SerialOutputStream
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_00024SerialOutputStream_write
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
