/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xeij_OldSerialPort_SerialInputStream */

#ifndef _Included_xeij_OldSerialPort_SerialInputStream
#define _Included_xeij_OldSerialPort_SerialInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef xeij_OldSerialPort_SerialInputStream_MAX_SKIP_BUFFER_SIZE
#define xeij_OldSerialPort_SerialInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#undef xeij_OldSerialPort_SerialInputStream_DEFAULT_BUFFER_SIZE
#define xeij_OldSerialPort_SerialInputStream_DEFAULT_BUFFER_SIZE 16384L
#undef xeij_OldSerialPort_SerialInputStream_MAX_BUFFER_SIZE
#define xeij_OldSerialPort_SerialInputStream_MAX_BUFFER_SIZE 2147483639L
/*
 * Class:     xeij_OldSerialPort_SerialInputStream
 * Method:    available
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xeij_OldSerialPort_00024SerialInputStream_available
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort_SerialInputStream
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xeij_OldSerialPort_00024SerialInputStream_close
  (JNIEnv *, jobject);

/*
 * Class:     xeij_OldSerialPort_SerialInputStream
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_xeij_OldSerialPort_00024SerialInputStream_read
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
